[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

build_flags = 
    ; --- CONFIGURACIÓN DE PANTALLA (TUS PINES CONFIRMADOS) ---
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D ESP32_PARALLEL=1
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4
    -D TFT_WR=15
    -D TFT_RD=-1
    -D TFT_D0=12
    -D TFT_D1=13
    -D TFT_D2=14
    -D TFT_D3=27
    -D TFT_D4=16
    -D TFT_D5=17
    -D TFT_D6=18
    -D TFT_D7=19
    
    ; --- CONFIGURACIÓN NRF24L01 ---
    -D NRF_SCK=25
    -D NRF_MISO=26
    -D NRF_MOSI=33
    -D NRF_CE1=21
    -D NRF_CSN1=32
    

    ; --- CONFIGURACIÓN DE BOTONES ---
    -D BTN_UP=34
    -D BTN_SEL=35
    -D BTN_DWN=23
    -D SUPPORT_TRANSACTIONS=1
    -D ESP32_DMA=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    nrf24/RF24 @ ^1.4.10